"""Utility classes and functions shared across action primitives.

This module centralizes common helpers so interaction builders remain
consistent and easy to reason about.
"""

from __future__ import annotations

import logging
from collections.abc import MutableMapping
from typing import TYPE_CHECKING, Any, Union

from action_primitives.constants import CardSource, SymbolName
from models.board_utils import BoardColorIterator

if TYPE_CHECKING:
    from action_primitives.base import ActionContext
    from models.card import Card
    from schemas.websocket_messages import DogmaInteractionRequest

logger = logging.getLogger(__name__)

PLAYER_ID_FIELD = "player_id"
GAME_ID_FIELD = "game_id"
INTERACTION_DATA_FIELD = "data"
TARGET_PLAYER_FIELDS: tuple[str, ...] = (
    PLAYER_ID_FIELD,
    "target_player_id",
    "source_player",
)

InteractionMapping = MutableMapping[str, Any]
InteractionPayload = Union["DogmaInteractionRequest", InteractionMapping]


def attach_player_to_interaction(
    interaction_request: InteractionPayload | None,
    player_id: str | None,
    game_id: str | None = None,
) -> InteractionPayload | None:
    """Attach routing metadata to an interaction payload.

    The function works with both mutable mappings (``dict``-like payloads) and
    Pydantic ``DogmaInteractionRequest`` models generated by the
    :class:`StandardInteractionBuilder`. Metadata is only attached when a
    ``player_id`` is provided – missing identifiers are logged so issues surface
    quickly instead of failing silently.
    """

    if interaction_request is None:
        logger.warning(
            "Received empty interaction request; cannot attach metadata",
            extra={"player_id": player_id, "game_id": game_id},
        )
        return interaction_request

    if not player_id:
        logger.warning(
            "Missing player_id while attempting to attach interaction metadata",
            extra={
                "game_id": game_id,
                "interaction_type": type(interaction_request).__name__,
            },
        )
        return interaction_request

    attached = False
    failure_context: dict[str, Any] | None = None

    try:
        if hasattr(interaction_request, PLAYER_ID_FIELD):
            setattr(interaction_request, PLAYER_ID_FIELD, player_id)
            attached = True
            if game_id and hasattr(interaction_request, GAME_ID_FIELD):
                setattr(interaction_request, GAME_ID_FIELD, game_id)
            # Also set target_player_id in data dict for interaction types
            if hasattr(interaction_request, "data") and isinstance(interaction_request.data, dict):
                interaction_request.data["target_player_id"] = player_id
        elif isinstance(interaction_request, MutableMapping):
            interaction_request.setdefault(PLAYER_ID_FIELD, player_id)
            attached = True
            if game_id:
                interaction_request.setdefault(GAME_ID_FIELD, game_id)
        else:
            failure_context = {
                "player_id": player_id,
                "game_id": game_id,
                "interaction_type": type(interaction_request).__name__,
                "reason": "unsupported_type",
            }
    except Exception:
        logger.error(
            "Failed to attach player metadata to interaction request",
            extra={"player_id": player_id, "game_id": game_id},
            exc_info=True,
        )
        failure_context = {
            "player_id": player_id,
            "game_id": game_id,
            "interaction_type": type(interaction_request).__name__,
            "reason": "exception",
        }

    if not attached:
        logger.warning(
            "Interaction payload did not expose mutable player metadata fields",
            extra=failure_context
            or {
                "player_id": player_id,
                "game_id": game_id,
                "interaction_type": type(interaction_request).__name__,
                "reason": "immutable_payload",
            },
        )

    return interaction_request


class CardSourceResolver:
    """
    Centralized card source resolution logic.
    Eliminates duplication across action primitives.
    """

    @staticmethod
    def get_cards(context: ActionContext, source: str) -> list[Card]:
        """
        Get cards from a specified source.

        Args:
            context: The action context containing game state
            source: Source identifier (e.g., "hand", "board", variable name)

        Returns:
            List of cards from the specified source
        """
        # Check for age deck sources FIRST (before variables) to prevent collision
        # Support both "age_X" and "deck_X" formats
        if source.startswith("age_") and source[4:].isdigit():
            age = int(source[4:])
            if hasattr(context.game, "age_decks") and age in context.game.deck_manager.age_decks:
                return context.game.deck_manager.age_decks[age].copy()
            return []
        elif source.startswith("deck_") and source[5:].isdigit():
            age = int(source[5:])
            if hasattr(context.game, "age_decks"):
                logger.info(f"DEBUG CardSourceResolver: Looking for age {age} in age_decks")
                logger.info(f"DEBUG CardSourceResolver: age_decks keys = {list(context.game.deck_manager.age_decks.keys())}")
                logger.info(f"DEBUG CardSourceResolver: age {age} in keys? {age in context.game.deck_manager.age_decks}")
                if age in context.game.deck_manager.age_decks:
                    cards = context.game.deck_manager.age_decks[age]
                    logger.info(f"DEBUG CardSourceResolver: Found {len(cards)} cards in age {age} deck")
                    # CRITICAL FIX: Return actual list, not copy, so TransferCards can remove cards
                    # FilterCards + TransferCards pattern requires same Card object references
                    return cards
                else:
                    logger.warning(f"DEBUG CardSourceResolver: Age {age} NOT found in age_decks")
            return []

        # Check if source is a variable second
        if source in context.variables:
            cards = context.get_variable(source, [])
            # Ensure we always return a list
            if not isinstance(cards, list):
                cards = [cards] if cards else []
            return cards

        # Handle player sources
        player = context.player
        if not player:
            logger.warning(f"No player in context for source: {source}")
            return []

        # Standard player locations
        if source == CardSource.HAND:
            return player.hand.copy()
        elif source == CardSource.BOARD or source == "board_top":
            return player.board.get_top_cards()
        elif source == CardSource.SCORE_PILE:
            return player.score_pile.copy()
        elif source == CardSource.ACHIEVEMENTS:
            return player.achievements.copy()

        # Board-specific sources
        elif source == CardSource.BOARD_ALL:
            # All cards on board (not just top)
            all_cards = []
            if player.board:
                for color in ["red", "blue", "green", "yellow", "purple"]:
                    cards_attr = f"{color}_cards"
                    if hasattr(player.board, cards_attr):
                        all_cards.extend(getattr(player.board, cards_attr, []))
            return all_cards
        elif source == CardSource.BOARD_BOTTOM or source == "board_bottom":
            # Bottom card from each color stack (index 0)
            bottom_cards = []
            if player.board:
                for color in ["red", "blue", "green", "yellow", "purple"]:
                    cards_attr = f"{color}_cards"
                    if hasattr(player.board, cards_attr):
                        color_stack = getattr(player.board, cards_attr, [])
                        if color_stack:  # Only add if stack has cards
                            bottom_cards.append(color_stack[0])  # First card is bottom
            return bottom_cards

        # Special references from action execution
        elif source == CardSource.LAST_DRAWN:
            return context.get_variable(CardSource.LAST_DRAWN, [])
        elif source == "last_drawn_all":
            # Support for accumulated drawn cards from RepeatAction
            cards = context.get_variable("last_drawn_all", [])
            # Ensure we always return a list
            if not isinstance(cards, list):
                cards = [cards] if cards else []
            return cards
        elif source == CardSource.DRAWN_CARD:
            drawn = context.get_variable(CardSource.DRAWN_CARD, None)
            return [drawn] if drawn else []
        elif source == CardSource.LOWEST_CARD:
            lowest = context.get_variable(CardSource.LOWEST_CARD, None)
            return [lowest] if lowest else []
        elif source == CardSource.HIGHEST_CARD:
            highest = context.get_variable(CardSource.HIGHEST_CARD, None)
            return [highest] if highest else []
        elif source == CardSource.SELECTED_CARDS:
            return context.get_variable(CardSource.SELECTED_CARDS, [])
        elif source == CardSource.FILTERED_CARDS:
            return context.get_variable(CardSource.FILTERED_CARDS, [])
        elif source == "filtered":
            # Support for FilterCards -> SelectCards pipeline
            return context.get_variable("filtered", [])

        # Opponent sources
        elif source == CardSource.OPPONENT_HAND:
            # Get cards from all opponents' hands
            opponent_cards = []
            if hasattr(context.game, "players"):
                for p in context.game.players:
                    if p.id != player.id:
                        opponent_cards.extend(p.hand)
            return opponent_cards

        # Demanding player sources (for demand effects)
        elif source == "demanding_player_hand":
            # Get cards from the demanding player's hand (active player in demand context)
            demanding_player = context.get_variable("demanding_player") or getattr(
                context, "demanding_player", None
            )
            logger.info(f"DEBUG demanding_player_hand: demanding_player={demanding_player.name if demanding_player else None}, hand_size={len(demanding_player.hand) if demanding_player else 0}")
            if demanding_player:
                cards = list(demanding_player.hand)
                logger.info(f"  Cards: {[c.name for c in cards]}")
                return cards
            logger.warning("demanding_player_hand: No demanding_player found in context!")
            return []
        elif source == CardSource.OPPONENT_BOARD:
            # Get top cards from all opponents' boards
            opponent_cards = []
            if hasattr(context.game, "players"):
                for p in context.game.players:
                    if p.id != player.id:
                        opponent_cards.extend(p.board.get_top_cards())
            return opponent_cards
        elif source == CardSource.OPPONENT_SCORE_PILE:
            # Get cards from all opponents' score piles
            opponent_cards = []
            if hasattr(context.game, "players"):
                for p in context.game.players:
                    if p.id != player.id:
                        opponent_cards.extend(p.score_pile)
            return opponent_cards

        # String source mappings for compatibility
        elif source == "hand":
            return player.hand.copy()
        elif source == "score" or source == "score_pile":
            return player.score_pile.copy()
        elif source == "board":
            return player.board.get_top_cards()
        elif source == "achievements":
            return player.achievements.copy()
        elif source == "achievements_available":
            # Get all available achievement cards from the game
            all_achievements = []
            if hasattr(context.game, "achievement_cards"):
                for age, cards in context.game.deck_manager.achievement_cards.items():
                    all_achievements.extend(cards)
            return all_achievements
        elif source == "reveal":
            # Support for cards in reveal location (temporary holding)
            return context.get_variable("reveal", [])
        elif source == "junk" or source == "junk_pile":
            # Support for junk pile
            if hasattr(context.game, "junk_pile"):
                return context.game.junk_pile.copy()
            return []
        elif source == "special_achievements_available":
            # Get Card objects for available special achievements
            if hasattr(context.game, "deck_manager") and hasattr(context.game.deck_manager, "special_achievements_available"):
                achievement_names = context.game.deck_manager.special_achievements_available
                special_dict = context.game.deck_manager.special_achievements
                return [special_dict[name] for name in achievement_names if name in special_dict]
            return []
        elif source == "special_achievements_junk":
            # Get Card objects for junked special achievements
            if hasattr(context.game, "deck_manager") and hasattr(context.game.deck_manager, "special_achievements_junk"):
                achievement_names = context.game.deck_manager.special_achievements_junk
                special_dict = context.game.deck_manager.special_achievements
                return [special_dict[name] for name in achievement_names if name in special_dict]
            return []

        # Invalid source - log warning
        logger.warning(f"Invalid card source: {source}")
        return []

    @staticmethod
    def get_single_card(context: ActionContext, source: str) -> Card | None:
        """
        Get a single card from a source.
        Returns None if source is empty or has multiple cards.

        Args:
            context: The action context
            source: Source identifier

        Returns:
            Single card or None
        """
        cards = CardSourceResolver.get_cards(context, source)
        if len(cards) == 1:
            return cards[0]
        elif len(cards) > 1:
            logger.warning(f"Expected single card from {source}, got {len(cards)}")
        return None

    @staticmethod
    def count_cards(context: ActionContext, source: str) -> int:
        """
        Count cards in a source without retrieving them.
        More efficient for just checking counts.

        Args:
            context: The action context
            source: Source identifier

        Returns:
            Number of cards in the source
        """
        # For efficiency, check counts directly where possible
        if source == "hand" and context.player:
            return len(context.player.hand)
        elif source == "score_pile" and context.player:
            return len(context.player.score_pile)
        elif source == "board" and context.player:
            return len(context.player.board.get_top_cards())

        # Fallback to getting cards and counting
        return len(CardSourceResolver.get_cards(context, source))


class CardFilterUtils:
    """
    Centralized card filtering logic.
    """

    @staticmethod
    def filter_by_age(
        cards: list[Card],
        min_age: int | None = None,
        max_age: int | None = None,
        exact_age: int | None = None,
    ) -> list[Card]:
        """Filter cards by age criteria."""
        if exact_age is not None:
            return [c for c in cards if c.age == exact_age]

        filtered = cards.copy()
        if min_age is not None:
            filtered = [c for c in filtered if c.age >= min_age]
        if max_age is not None:
            filtered = [c for c in filtered if c.age <= max_age]
        return filtered

    @staticmethod
    def filter_by_color(cards: list[Card], colors) -> list[Card]:
        """Filter cards by color.

        Args:
            cards: List of cards to filter
            colors: Color(s) to filter by - can be a single color (str/CardColor) or list of colors
        """
        # Normalize colors to a list of lowercase strings
        if not isinstance(colors, list):
            colors = [colors]

        # Convert each color to lowercase string
        normalized_colors = []
        for c in colors:
            if hasattr(c, 'value'):  # CardColor enum
                normalized_colors.append(str(c.value).lower())
            else:
                normalized_colors.append(str(c).lower())

        return [c for c in cards if c.color.value.lower() in normalized_colors]

    @staticmethod
    def filter_by_symbol(cards: list[Card], symbol: str) -> list[Card]:
        """Filter cards that contain a specific symbol."""
        from models.card import Symbol

        symbol_map = {
            SymbolName.CIRCUIT: Symbol.CIRCUIT,
            SymbolName.DATA: Symbol.DATA,
            SymbolName.ALGORITHM: Symbol.ALGORITHM,
            SymbolName.NEURAL_NET: Symbol.NEURAL_NET,
            SymbolName.ROBOT: Symbol.ROBOT,
            SymbolName.HUMAN_MIND: Symbol.HUMAN_MIND,
        }

        required_symbol = symbol_map.get(symbol.lower())
        if not required_symbol:
            logger.warning(f"Invalid symbol for filtering: {symbol}")
            return []

        return [c for c in cards if required_symbol in c.symbols]

    @staticmethod
    def filter_by_board_colors(
        cards: list[Card],
        context: ActionContext,
        same_as_board: bool = False,
        different_from_board: bool = False,
    ) -> list[Card]:
        """Filter cards based on colors present on player's board."""
        if not context.player or not context.player.board:
            return []

        board_colors = BoardColorIterator.get_board_colors_set(context.player.board)

        if same_as_board:
            return [c for c in cards if c.color.value in board_colors]
        elif different_from_board:
            return [c for c in cards if c.color.value not in board_colors]

        return cards

    @staticmethod
    def filter_highest(cards: list[Card]) -> list[Card]:
        """Filter cards to only include those with the highest age."""
        if not cards:
            return []

        max_age = max(c.age for c in cards)
        return [c for c in cards if c.age == max_age]

    @staticmethod
    def filter_lowest(cards: list[Card]) -> list[Card]:
        """Filter cards to only include those with the lowest age."""
        if not cards:
            return []

        min_age = min(c.age for c in cards)
        return [c for c in cards if c.age == min_age]


class ActionLogger:
    """
    Centralized logging for action results.
    """

    @staticmethod
    def log_card_transfer(
        context: ActionContext,
        cards: list[Card],
        from_location: str,
        to_location: str,
        target_player: str | None = None,
    ) -> None:
        """Log a card transfer action."""
        if not cards:
            return

        count = len(cards)

        # Build descriptive message
        if count == 1:
            card = cards[0]
            card_desc = f"{card.name} (age {card.age})"
        else:
            card_desc = f"{count} cards"

        if target_player and target_player != context.player.name:
            message = f"transferred {card_desc} from {from_location} to {target_player}'s {to_location}"
        else:
            message = f"moved {card_desc} from {from_location} to {to_location}"

        context.add_result(message)

    @staticmethod
    def log_card_draw(context: ActionContext, cards: list[Card], age: int) -> None:
        """Log a card draw action."""
        if not cards:
            context.add_result(f"No cards available to draw from age {age}")
            return

        count = len(cards)
        if count == 1:
            context.add_result(f"drew {cards[0].name} from age {age}")
        else:
            context.add_result(f"drew {count} cards from age {age}")

    @staticmethod
    def log_selection_required(
        context: ActionContext,
        eligible_count: int,
        required_count: int,
        selection_type: str = "cards",
    ) -> None:
        """Log that a selection is required."""
        if required_count == 1:
            context.add_result(
                f"Waiting for selection of 1 {selection_type} from {eligible_count} options"
            )
        else:
            context.add_result(
                f"Waiting for selection of {required_count} {selection_type} from {eligible_count} options"
            )
