"""
Plan Caching - LRU cache for commonly-used execution plans.

This module implements Phase 9 from the Action Scheduler specification,
providing performance improvements by caching repeated execution patterns.
"""

import hashlib
import json
from collections import OrderedDict
from dataclasses import dataclass


@dataclass
class CacheStatistics:
    """Statistics for cache performance monitoring."""

    hits: int = 0
    misses: int = 0
    evictions: int = 0
    total_requests: int = 0

    @property
    def hit_rate(self) -> float:
        """Calculate cache hit rate as percentage."""
        if self.total_requests == 0:
            return 0.0
        return (self.hits / self.total_requests) * 100.0

    @property
    def miss_rate(self) -> float:
        """Calculate cache miss rate as percentage."""
        if self.total_requests == 0:
            return 0.0
        return (self.misses / self.total_requests) * 100.0

    def reset(self) -> None:
        """Reset all statistics to zero."""
        self.hits = 0
        self.misses = 0
        self.evictions = 0
        self.total_requests = 0


class PlanCache:
    """
    LRU cache for ActionPlans to avoid redundant plan creation.

    Caches plans by effect structure and player configuration.
    Uses OrderedDict for efficient LRU eviction.

    Design:
    - Key: Hash of (effect structure, player IDs, plan type)
    - Value: Serialized ActionPlan (dict from to_dict())
    - Eviction: LRU when max_size exceeded
    - Thread-safe: Not required (single-threaded async execution)
    """

    def __init__(self, max_size: int = 100):
        """
        Initialize plan cache.

        Args:
            max_size: Maximum number of plans to cache (default: 100)
        """
        self.max_size = max_size
        self._cache: OrderedDict[str, dict] = OrderedDict()
        self.stats = CacheStatistics()

    def get(self, cache_key: str) -> dict | None:
        """
        Retrieve plan from cache.

        Args:
            cache_key: Cache key generated by _generate_cache_key()

        Returns:
            Serialized plan dict if cached, None if not found

        Side Effects:
            - Updates LRU order (moves to end)
            - Updates statistics
        """
        self.stats.total_requests += 1

        if cache_key in self._cache:
            # Move to end (most recently used)
            self._cache.move_to_end(cache_key)
            self.stats.hits += 1
            return self._cache[cache_key]

        self.stats.misses += 1
        return None

    def put(self, cache_key: str, plan_dict: dict) -> None:
        """
        Store plan in cache.

        Args:
            cache_key: Cache key generated by _generate_cache_key()
            plan_dict: Serialized plan from ActionPlan.to_dict()

        Side Effects:
            - Evicts LRU entry if cache full
            - Updates statistics
        """
        # If key exists, update it and move to end
        if cache_key in self._cache:
            self._cache.move_to_end(cache_key)
            self._cache[cache_key] = plan_dict
            return

        # Check if cache is full
        if len(self._cache) >= self.max_size:
            # Evict least recently used (first item)
            self._cache.popitem(last=False)
            self.stats.evictions += 1

        # Add new entry
        self._cache[cache_key] = plan_dict

    def clear(self) -> None:
        """Clear all cached plans."""
        self._cache.clear()

    def __len__(self) -> int:
        """Return number of cached plans."""
        return len(self._cache)

    @staticmethod
    def generate_cache_key(
        plan_type: str,
        effects: list[list[dict]],
        player_ids: list[str],
    ) -> str:
        """
        Generate cache key from plan parameters.

        Cache Key Design:
        - Must uniquely identify plan structure
        - Must be consistent for identical plans
        - Must be fast to compute

        Key Components:
        - plan_type: "sharing" or "execution"
        - effect_structure: JSON of effect primitives
        - player_ids: Sorted list of player IDs

        Args:
            plan_type: Type of plan ("sharing" or "execution")
            effects: List of effects (each effect is list of action primitives)
            player_ids: List of player IDs in execution order

        Returns:
            Hash string suitable for cache key
        """
        # Create deterministic structure for hashing
        # For execution plans, sort player_ids for deterministic cache keys
        # For sharing plans, preserve order (clockwise execution matters)
        sorted_player_ids = (
            sorted(player_ids) if plan_type == "execution" else player_ids
        )

        key_data = {
            "plan_type": plan_type,
            "effects": effects,
            "player_ids": sorted_player_ids,
        }

        # Serialize to JSON (sorted keys for consistency)
        json_str = json.dumps(key_data, sort_keys=True)

        # Hash to fixed-length string
        return hashlib.sha256(json_str.encode()).hexdigest()
